### ISSUE TITLE
多线程安全

### ISSUE THREAD

**Issue by wen1q84** [ShannonAI/service-streamer#45]
https://github.com/ShannonAI/service-streamer/blob/ebcc3724efc9789feb8980641533909798d4d6dc/service_streamer/service_streamer.py#L102
你好，这个_future_cache在多线程访问时不需要用锁保护下么

**Comment by Meteorix** [comment]
@wen1q84 你好，python的built-in容器可以当作线程安全的，因为gil的存在。https://docs.python.org/3/glossary.html#term-global-interpreter-lock

**Comment by wen1q84** [comment]
https://github.com/ShannonAI/service-streamer/blob/ebcc3724efc9789feb8980641533909798d4d6dc/service_streamer/service_streamer.py#L96
这个task_id为什么要用锁保护呢

**Comment by Meteorix** [comment]
因为taskid并不是容器类型

wen1q84 <notifications@github.com>于2019年11月15日 周五下午5:10写道：
