### ISSUE TITLE
一个及其严重的BUG

### ISSUE THREAD

**Issue by li1191863273** [ShannonAI/service-streamer#48]
在实现ManagedModel接口，覆写predict方法，在正常的使用中，如果predict方法出现异常，会导致后续所有的调用Timeout

**Comment by leon0707** [comment]
https://github.com/ShannonAI/service-streamer/blob/master/service_streamer/service_streamer.py#L188

model_predict出现的异常并没有处理

**Comment by Meteorix** [comment]
建议可以先在自己的predict接口中catch一下异常，这个api我们考虑下容错

**Comment by li1191863273** [comment]
已经try cactch了

**Comment by songyouwei** [comment]
这个api容错怎么做比较优雅一点呢，只能except返回None值？
