### ISSUE TITLE
多gpu设置时只设置cuda_devices=(2,3)不起作用，仍然使用0，1，2，3四块卡

### ISSUE THREAD

**Issue by lingdavid** [ShannonAI/service-streamer#53]
streamer = Streamer(ManagedBertModel, batch_size=64, max_latency=0.1, worker_num=4, cuda_devices=(2, 3))

![image](https://user-images.githubusercontent.com/25095662/71873314-d4303180-3159-11ea-8ce8-dc1c4d8106d8.png)
基本上是按照flask_multigpu_example.py文件来写的。

**Comment by yangtianyu92** [comment]
export CUDA_VISIBLE_DEVICES=2,3      你试试，应该能解决你的问题。我就是这么做的。
