### ISSUE TITLE
在cpu上能获得加速吗？

### ISSUE THREAD

**Issue by gikerch** [ShannonAI/service-streamer#57]
在cpu上能获得加速吗？我打印出来的batch都是1

**Comment by qiuwei** [comment]
cpu 调大batch 也没啥用，离线情况下batchify以后 差不多能得到1.2的加速比，但是考虑这里你需要等一段时间凑齐batch，所以可以认为几乎没有加速。

**Comment by gikerch** [comment]
谢谢，我尝试过了，有一定效果，wrk 并发测下来大概有3-4倍的提升

**Comment by alanwang93** [comment]
> cpu 调大batch 也没啥用，离线情况下batchify以后 差不多能得到1.2的加速比，但是考虑这里你需要等一段时间凑齐batch，所以可以认为几乎没有加速。

CPU调大batch还是有用的吧，我测试的结果和batch size=10能比batch_size=1快6-7倍。
